apiVersion: apps/v1
kind: Deployment

metadata:
  name: bank-api

spec:
  replicas: 3

  selector:
    matchLabels:
      app: bank-api

  template:
    metadata:
      labels:
        app: bank-api

    spec:
      containers:
        - name: bank-api
          image: ghcr.io/ominderoen2-cloud/bank:2b23886803ed628d0a64611847bdc210a8e9dd8b
          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          envFrom:
            - configMapRef:
                name: bank-config

            - secretRef:
                name: bank-secret